import type { Metadata } from "next";
import Link from "next/link";
import { ArticleCard, Shell } from "./components";
import { articles, topics } from "./content";

export const metadata: Metadata = {
  alternates: { canonical: "/" },
};

export default function Home() {
  return <Shell>
    <section className="hero"><p className="eyebrow">Skyline by HC · Singapore</p><h1>Developer decisions shape construction outcomes <em>long before work begins on site.</em></h1><div className="hero-bottom"><div><p>Lim Hwee Chim is a Singapore property development leader and the founder of Skyline by HC, where she writes about how upstream developer decisions shape construction outcomes.</p><p className="hero-mission">Skyline by HC is her effort to ensure that hard-won lessons do not disappear when a project ends. Through writing, she explores the invisible decisions, coordination and human judgement behind the built environment—turning difficult experiences into useful questions, practical experiments and lessons that may help others understand, improve and find their place in this industry.</p></div><div className="hero-actions"><Link className="button primary" href="/articles">Start with selected articles <span>→</span></Link><Link className="text-link" href="/about">About Lim Hwee Chim <span>→</span></Link></div></div></section>
    <section className="beliefs section-pad" aria-labelledby="beliefs-heading"><div className="beliefs-intro"><p className="eyebrow">What guides Skyline by HC</p><h2 id="beliefs-heading">Three beliefs behind the work.</h2><p>Skyline by HC is shaped by three beliefs about how the built environment can be understood, improved and shared.</p></div><div className="belief-grid"><article><span>01</span><h3>Reveal the invisible work.</h3><p>Buildings are shaped long before construction becomes visible. Skyline traces outcomes back to the decisions, information, interfaces and people behind them—making often-unseen contributions easier to understand.</p></article><article><span>02</span><h3>Turn hard problems into disciplined experiments.</h3><p>Project difficulties can become questions to investigate: understand the system, test a practical intervention and examine what genuinely changes.</p></article><article><span>03</span><h3>Never waste a lesson.</h3><p>Hard-won experience should not disappear into archived emails or individual memory. Skyline turns project observations into reusable principles so future decisions—and other practitioners—can begin further ahead.</p></article></div><p className="beliefs-principle">Together, these beliefs support one central idea: better downstream outcomes begin with better upstream conditions.</p></section>
    <section className="feature"><div className="feature-label"><span>Featured essay</span><span>01</span></div><div className="feature-copy"><p className="eyebrow">{articles[0].topic} · {articles[0].read} read</p><h2><Link href={`/articles/${articles[0].slug}`}>{articles[0].title}</Link></h2><p>{articles[0].dek}</p><Link className="read-link" href={`/articles/${articles[0].slug}`}>Read the essay <span>↗</span></Link></div><div className="feature-art" aria-hidden="true"><span>Upstream</span><i></i><span>Outcome</span></div></section>
    <section className="latest section-pad"><div className="section-head"><div><p className="eyebrow">Start here</p><h2>Three ways into the work.</h2><p className="section-intro">A selection across delivery, regulation and technology—the recurring places where upstream choices become visible downstream.</p></div><Link className="text-link" href="/articles">View all articles <span>→</span></Link></div><div className="article-grid">{[articles[1],articles[2],articles[4]].map((a,i)=><ArticleCard key={a.slug} article={a} index={i+1}/>)}</div></section>
    <section className="topics-home section-pad"><div className="topics-intro"><p className="eyebrow">The body of work</p><h2>Five lenses.<br/>One connected system.</h2><p>Construction is often treated as a site problem. Skyline looks further upstream—at how developer intent travels through policy, procurement, design and delivery.</p></div><div className="topic-list">{topics.map((t,i)=><Link href={`/topics/${t.slug}`} key={t.slug}><span>{String(i+1).padStart(2,"0")}</span><strong>{t.title}</strong><i>→</i></Link>)}</div></section>
    <section className="practice section-pad"><div className="practice-title"><p className="eyebrow">Practitioner perspective</p><h2>Across the development lifecycle, not from one isolated vantage point.</h2><p>Skyline connects decisions that are often discussed separately—from feasibility and authority strategy to procurement, delivery and completion.</p><Link className="text-link" href="/about">Read the full perspective <span>→</span></Link></div><div className="evidence-list"><article><span>01</span><h3>Developer-side view</h3><p>Examining the conditions developers create for consultants, contractors and project teams.</p></article><article><span>02</span><h3>Project-grounded writing</h3><p>Testing ideas against real delivery pressure, practical constraints and competing responsibilities.</p></article><article><span>03</span><h3>System-level focus</h3><p>Following how information, interfaces and time move from early decisions into construction outcomes.</p></article><article><span>04</span><h3>Industry contribution</h3><p>Turning field experience into useful conversations on productivity, technology, regulation and leadership.</p></article></div></section>
    <section className="quote"><blockquote>“Good developer interventions often create invisible value—in delays, disputes and variations that never occur.”</blockquote><p>— A recurring Skyline principle</p></section>
    <section className="dispatch section-pad"><div><p className="eyebrow">Connect</p><h2>Bring an interesting problem.</h2></div><p>If you are working through a construction issue, testing an idea, or see something worth discussing, feel free to get in touch.</p><Link className="button" href="/connect">Compare notes <span>→</span></Link></section>
  </Shell>;
}
