import type { Metadata } from "next"; import { notFound } from "next/navigation"; import Link from "next/link"; import { Shell } from "../../components"; import { articles } from "../../content";
export function generateStaticParams(){return articles.map(a=>({slug:a.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const a=articles.find(x=>x.slug===slug);return a?{title:`${a.title} | Skyline by HC`,description:a.dek,alternates:{canonical:`/articles/${a.slug}`},openGraph:{title:a.title,description:a.dek,type:"article"}}:{}}

function TopArticle(){return <>
  <p className="lead">The last tower crane came down over a weekend. By Monday, the site looked finished from the road: hoarding still up, the skyline above it complete, the towers finally matching the artist&apos;s impression released more than two and a half years earlier.</p>
  <p>There were about six months of work left. The last ninety of those days would decide whether the first ninety had been used properly.</p>
  <p>I used to record the cranes leaving as a milestone. It is closer to a starting gun for the part nobody photographs.</p>
  <p>On that project—1,008 units—TOP was not one inspection but a series of them. BCA, SCDF, NEA and PUB, each with its own date, its own queue and its own view of what a complete submission looks like. Every clearance had to close before the final stack could be filed at all.</p>
  <p>Each inspection lasts about a day. Preparing for each one takes the whole team days and nights: cleaning, protecting, re-checking, walking the route the officer will walk before the officer walks it. Then it happens again for the next agency.</p>
  <p>The certificate itself was issued the same day the stack went in. It took a day to issue and four years to deserve.</p>
  <p>People assume TOP is an inspection. It is a sequence of them, and the outcome of each is settled long before the date is booked.</p>

  <h2>The Illusion of Completion</h2>
  <p>With the cranes and passenger hoists removed six months before the targeted TOP, the buildings appeared completed, yet the development was far from it.</p>
  <p>From the road the project looks done. Up close, the towers may be substantially complete while the spaces residents will actually use are still taking shape: clubhouse, pools, playgrounds, arrival court, landscape, guardhouse, pavilions and function rooms. These come late.</p>
  <p>Unlike the residential floors, they do not repeat.</p>
  <p>A typical floor is built thirty or forty times. Catch a problem on floor six and you have thirty chances to get it right. Repetition is its own quality system.</p>
  <p>The amenity deck offers no such mercy. A curved handrail at a ramp appears exactly once. So does the feature staircase, the water wall, the sunken lounge, the three-way interface between landscape, structure and drainage where the falls have to work in both directions. Each has to be understood, coordinated and built correctly the first time. By the time a mistake is visible, the work around it is finished.</p>
  <p>This is why standardisation matters even on projects that want to feel distinctive. Consistent door families, railing details and interfaces are not a tax on design intent. They reduce the number of things the site team has to interpret from scratch, at the point where interpretation is most expensive.</p>
  <blockquote>Creativity sets the character of a project. Consistency delivers it.</blockquote>

  <h2>When Sequence Becomes Everything</h2>
  <p>For most of construction, progress is visible. Structure rises. Façades close. Rooms take shape. You can measure what has been cast and installed.</p>
  <p>The final months are different.</p>
  <p>Sprinklers wait for ceilings. Ceilings wait for services to be tested. Testing waits for permanent power, which waits for the LEW&apos;s endorsement and a switchroom that is clean, dry and locked. Condensers wait for ledges. Lift commissioning waits for water ingress to be resolved. Landscape planting waits for heavy access to stop, and the same landscape may be needed for a clearance.</p>
  <p>Float disappears. A three-day delay is rarely a three-day delay: it blocks the next trade, moves a test date, and spends a recovery window that no longer exists.</p>
  <p>The remaining work is not more technically difficult. It is difficult because the team has fewer choices left.</p>
  <p>A design issue found two years out has several solutions. The same issue found two weeks before inspection has one, and it is never the cheap one.</p>
  <p>Time lost upstream does not disappear. It comes back near TOP as extra manpower, repeated testing, temporary protection, night work, and decisions made faster than anyone would like.</p>

  <h2>From Building to System</h2>
  <p>About ninety days out, the project stops behaving like a collection of buildings and starts behaving like one system.</p>
  <p>For years the meetings were about physical progress: concrete, façade closure, finishes, percentage complete. Then the conversation changes.</p>
  <p>Lifts must home correctly when the alarm is triggered. The generator must pick up load, not merely start. Staircase pressurisation must hold with the doors open, which is the condition that matters and the one people forget to test. Access-controlled doors must release on the right emergency signal, and only that one.</p>
  <p>Every component works. That is not the same as the building working.</p>
  <p>TOP exposes the interfaces. The fire alarm panel works. The lift works. The problem appears only when the alarm sounds and the lift goes nowhere in particular. That failure sits inside nobody&apos;s package. It lives between packages, drawings and scopes, which is exactly why nobody has been chasing it.</p>
  <p>Near TOP, the building stops being a collection of completed components. Each fan, alarm and control sequence must work as part of one system.</p>
  <p>This is why the last ninety days feel disproportionate to the work remaining. The project is no longer testing whether the trades finished. It is testing whether they can coexist.</p>

  <h2>The Least Damaging Compliant Answer</h2>
  <p>A pipe, duct or bracket may have been installed slightly differently from the coordinated drawing. Found early, the response is simple: identify, correct, continue.</p>
  <p>Found near TOP, the ceiling above it is closed, the finishes are done, and the adjacent systems have already passed testing. Restoring the drawing means reopening finished work that is performing perfectly well.</p>
  <p>Sometimes that is still the right answer.</p>
  <p>More often the controlled solution is to verify that the installed element is sound and code-compliant, then move the coordination around it. This is uncomfortable. The item that ignored the drawing stays. Everything that followed the drawing moves. Complex systems do not optimise for fairness between trades. They optimise for the most stable outcome available.</p>
  <p>The compliance standard does not move. The revised arrangement is still reviewed, documented, endorsed and tested. Only the route changes.</p>
  <p>Near TOP, leadership is rarely about finding the perfect answer. It is about choosing the least damaging compliant one, and being able to stand behind it afterwards.</p>

  <h2>What Rain Finds</h2>
  <p>Rain does not read the programme. It finds the weak point, and near TOP that honesty gets expensive.</p>
  <p>Water in an unfinished basement is manageable. Water in a lift pit, an electrical room or a completed finish stops testing and starts a cycle of drying, investigation, rectification and retesting.</p>
  <p>Rain is almost never the cause. It exposes a construction joint nobody resolved, a waterproofing interface buried behind later work, a temporary opening left open too long, a sequence compressed before the building was protected.</p>
  <p>By the time the leak appears, the decision behind it is months old. The weather takes the blame because the weather is visible.</p>

  <h2>The Evidence Behind the Building</h2>
  <p>A project can look ready and still be unable to obtain TOP.</p>
  <p>The building is only part of the evidence. The team also has to produce as-built drawings, test and commissioning records, the QP&apos;s endorsements, and clearances it does not control—fire safety, lift permits, drainage and sanitary, vector control. None of them can be accelerated by pressure, and any one of them can hold the whole stack.</p>
  <p>These records get treated as administration to tidy up afterwards. That is an expensive assumption. Test results take time to compile. As-built drawings have to show what was installed, not the tender drawings with a new title block. If documentation only begins when the physical work ends, the project may find that the evidence it holds no longer matches the building it built.</p>
  <p>Authorities cannot approve what the team cannot substantiate. An unfinished wall has someone standing in front of it. A missing test record has nobody, and stays missing until the submission is being assembled.</p>

  <h2>The Authority Lens</h2>
  <p>Developers, consultants and contractors experience a project through delivery. We remember the late nights, the manpower shortfalls, the design changes, the problems solved along the way.</p>
  <p>The officer sees none of that, and should not. The question is not what the project endured. It is whether the completed development is safe, functional and fit to be occupied. Effort is not evidence.</p>
  <p>This feels severe in the final weeks, when everyone is exhausted and one observation threatens another round of work. The distance is the point. Residents inherit the building, not the difficulty of building it.</p>

  <h2>One Thousand and Eight Units</h2>
  <p>The final quality clearance is not a single inspection date either. CONQUAS assesses a sample. The Quality Mark does not—all 1,008 units are assessed and closed out individually.</p>
  <p>That means sequencing access to 1,008 units: finishes complete, work protected, assessment arranged, observations closed, batches re-presented where necessary. None of it can start in the final ninety days. On this scale the programme has to begin one to two years before TOP, while construction is still running elsewhere on site. It is not a task that responds to urgency.</p>
  <p>The visible deadline is TOP. The real programme starts much earlier.</p>
  <p>This project carried one more layer. We had signed on to the pilot Whole-of-Government inspection framework with BCA, which requires the separate agency inspections to converge through one coordinated process rather than arriving in their own time. It turned a demanding completion phase into a more interesting stress test than the one we had planned for. That deserves an essay of its own, once the lessons have settled.</p>

  <h2>What TOP Actually Tests</h2>
  <p>TOP looks like the end of construction. It is closer to an audit of whether decisions made by different people over several years can converge into one working outcome.</p>
  <p>The most valuable interventions are invisible by then. A design interface resolved early does not appear on any checklist. Neither does the dry-run test arranged before the formal one, the opening sealed before the monsoon, or the documentation gap caught months before submission.</p>
  <blockquote>Nothing happens. That is the value.</blockquote>
  <p>TOP was issued within hours of the final submission, and after the preceding months it felt almost anticlimactic. There was no decisive act. The project was ready because a large number of people had been quietly closing small gaps for a very long time. The inspections took days. The preparation took years.</p>
  <p>TOP is not really an inspection. It is the point at which a project can no longer hide the quality of everything that came before it.</p>
  <p className="original-note">Originally published on <a href="https://www.linkedin.com/pulse/top-90-day-stress-test-hwee-chim-lim-0nz0c/" target="_blank" rel="noreferrer">LinkedIn</a> on 30 July 2026.</p>
  <p className="author-note">Lim Hwee Chim is a Singapore property development leader and the founder of Skyline by HC, where she writes about how upstream developer decisions shape construction outcomes.</p>
</>}

function BetArticle(){return <>
  <p className="lead">The scheme made advanced construction commercially attractive to developers. As yesterday’s innovations become today’s baseline, what should the next incentive reward?</p>
  <p>Three percent sounds small until someone draws it.</p>
  <p>On a development with 100,000 square metres of permissible GFA, three percent represents another 3,000 square metres of floor area. It may not increase the allowable number of homes, and it remains subject to planning constraints and the overall bonus-GFA cap. Even so, it can create enough value to alter a project’s feasibility—and enough interest to bring a developer back to the meeting table.</p>
  <p>This was the attraction of the Built Environment Transformation Gross Floor Area Incentive Scheme, better known as BET GFA. Introduced in November 2021, it allows qualifying private developments to receive up to 3% bonus GFA for achieving higher standards in digitalisation, construction productivity, sustainability and maintainability.</p>
  <p>The Government offered developers something they understood well—additional development potential—in exchange for adopting methods that individual projects might not otherwise volunteer to fund.</p>
  <p>The bargain was unusually direct. Developers would commit to Integrated Digital Delivery, productive construction methods such as PPVC or advanced prefabrication, prefabricated MEP systems, higher quality and stronger environmental performance. The additional GFA helped offset part of the design effort, coordination burden, capital cost and adoption risk. Transformation had acquired a line in the feasibility spreadsheet. This tends to improve its chances of being discussed.</p>
  <p>BET has received less attention in recent years, particularly for Government Land Sales sites. This is not necessarily because the policy lost relevance. Many requirements that BET once incentivised have increasingly been incorporated into newer land-sale conditions. What was previously encouraged through additional GFA has gradually moved into the development baseline.</p>
  <p>Private sites, including many collective-sale redevelopments, may still qualify under the present scheme, subject to planning approval and the overall bonus-GFA budget. But BET expires on 23 November 2026. As technical assessment and planning must begin well before then, its practical runway is shorter than the calendar suggests.</p>
  <p>This may appear to be a narrow discussion about additional floor area. It is not. The more important question is what that floor area persuaded projects to do differently—and whether those behaviours will continue after the incentive disappears.</p>
  <h2>What BET was really designed to change</h2>
  <p>A steel mould for a PPVC module has little interest in the next drawing revision. Once fabrication begins, the apartment layout is no longer merely a design question. It has become a procurement commitment. The structural grid, façade interface, service openings, waterproofing details, tolerances and lifting points must already have been settled.</p>
  <p>By the time several hundred modules enter production, “adjust on site” is no longer much of a strategy. Unresolved information does not remain quietly inside a drawing register. It gets manufactured, repeatedly and with impressive efficiency.</p>
  <p>That is the discipline behind BET. The scheme did not merely encourage developers to purchase new technology. It required them to establish the conditions under which the technology could work: a clearer brief, earlier consultant coordination, sufficient design time, an aligned procurement strategy and construction knowledge brought into the room before important decisions became expensive to reverse.</p>
  <p>Integrated Digital Delivery, PPVC, prefabricated MEP and Green Mark Platinum Super Low Energy may appear as separate qualifying requirements. On an actual project, they depend on the same discipline: early integration. PPVC cannot be introduced efficiently after apartment layouts and structural grids have been fixed. Prefabricated MEP achieves little if risers, ceiling zones, access panels and equipment clearances remain unresolved.</p>
  <p>Higher energy performance becomes progressively more expensive once the building form, façade and plant strategy have been settled.</p>
  <p>Quality also moves upstream. In conventional construction, a service opening can sometimes be enlarged, a pipe diverted or a finishing detail adjusted on site. With greater prefabrication, one poorly coordinated bathroom or façade detail can be reproduced across hundreds of units before the first problem is discovered. The factory does not cure incomplete information. It reproduces it more consistently.</p>
  <p>BET therefore changed when projects had to make decisions. Developers establish the conditions; contractors execute within them. A contractor cannot recover during construction the coordination time that was never provided before tender.</p>
  <p>The deeper bargain was limited additional development value in exchange for developer-led changes in how a project was planned, coordinated and manufactured. Much of the resulting value remained invisible: clashes that never reached the site, modules that avoided redesign, defects that were not repeated across 1,000 units and variations that never entered the final account.</p>
  <h2>Why expiry is defensible</h2>
  <p>A transformation incentive should not become a permanent reward for practices the industry already knows how to deliver. APCS, PPVC, prefabricated MEP and digital coordination are no longer unfamiliar ideas. Some have become part of GLS conditions, while CORENET X is pulling multidisciplinary coordination further forward. Sustainability expectations are also moving into the regulatory and commercial baseline.</p>
  <p>Where a practice has become mandatory, widely adopted or part of ordinary procurement, the case for continuing to award valuable bonus GFA weakens. The incentive has then done part of its job. Continuing it unchanged would risk paying repeatedly for a transition that has already occurred.</p>
  <p>There are legitimate planning considerations too. Additional GFA creates development value, but it may also add building bulk, population intensity and demand on transport and infrastructure. A temporary catalyst should not quietly mature into a permanent planning entitlement merely because everyone has grown accustomed to including it in the feasibility spreadsheet.</p>
  <p>It is therefore reasonable to review whether BET’s present thresholds remain genuinely transformational and whether future support should reward verified outcomes rather than prescribed methods. Expiry would not necessarily mean the scheme failed. It may mean that its supported methods have moved closer to ordinary practice.</p>
  <blockquote>The question is whether the need for an upstream incentive has disappeared—or whether the frontier has simply moved beyond the current checklist.</blockquote>
  <h2>What the present checklist may no longer catch</h2>
  <p>The next meaningful construction advance may not fit neatly within today’s definitions of APCS or PPVC. It could involve automated reinforcement production, robotic finishing, autonomous inspection, AI-assisted quality control, greater off-site completion or components designed for disassembly and reuse. A hybrid system may also fall short of a prescribed percentage while producing better results in manpower, quality, waste or embodied carbon.</p>
  <p>These approaches face the same commercial problem BET was designed to address. The first projects carry the additional design work, integration burden, technical uncertainty and risk of failure. Later projects inherit the manufacturing capability, trained workforce, tested standards and lessons—usually at a lower price and with fewer surprises.</p>
  <p>A developer may reasonably ask why one project should pay to prove a system that the rest of the industry will later acquire more cheaply. That is not necessarily resistance to innovation. It is an allocation-of-risk question with a fairly honest answer.</p>
  <p>A successor to BET could therefore be smaller, more selective and technology-neutral. Rather than preserving the present checklist, it could support projects demonstrating measurable transformation beyond the prevailing baseline: material reductions in repetitive site labour, greater transfer of work into controlled manufacturing, better information continuity and verifiable improvements in quality, carbon, safety or maintainability.</p>
  <p>The test should be the integrated outcome, not the number of technologies accumulated. Five digital use cases do not necessarily create an integrated project. Sometimes they simply create five use cases. A high PPVC percentage does not guarantee good prefabrication, just as a high environmental rating does not guarantee that the completed building will perform as intended—or that anyone will enjoy maintaining it.</p>
  <blockquote>Compliance can count activities. Transformation must improve the system.</blockquote>
  <h2>Where en-bloc redevelopment fits</h2>
  <p>Collective-sale redevelopment deserves particular consideration, although being an en-bloc site should not create an automatic entitlement. Such projects inherit existing physical conditions rather than clean parcels structured around current requirements. There may be demolition constraints, legacy utilities, irregular boundaries, occupied surroundings and incomplete information about what lies below ground.</p>
  <p>The replacement development must nevertheless meet current expectations for accessibility, sustainability, buildability, maintainability and productivity. Planning parameters, unit yield, structural grids, prefabrication, façades, MEP distribution and sustainability measures must all be reconciled before the project commits to a design that works commercially but resists efficient construction.</p>
  <p>An upstream incentive can be especially useful here. It gives the developer both the discipline and a commercial reason to confront difficult coordination questions while they remain relatively inexpensive to resolve. En-bloc projects may therefore have more to gain from BET’s underlying principle, even if they should not receive bonus GFA merely because their sites are difficult.</p>
  <p>Acquisition risk, demolition and inherited conditions remain part of the commercial decision to purchase an existing estate. A stronger incentive tier would be defensible only where genuine redevelopment complexity is combined with transformation outcomes materially above the prevailing baseline. It would recognise the harder task of integrating advanced systems into a constrained redevelopment, not reward the act of buying an old estate.</p>
  <p>The distinction matters because anticipated bonus GFA may be capitalised into the collective-sale expectation before a consultant is appointed or a construction system considered. If the additional value is absorbed into the land price, little remains to support the transformation work it was meant to encourage.</p>
  <h2>The objection worth answering</h2>
  <p>The strongest objection to a technology-neutral scheme may come from the people required to administer it.</p>
  <p>Their argument is reasonable. A percentage is auditable. PPVC content can be measured, a Green Mark rating verified and a common data environment inspected. “Materially better outcomes” cannot be checked against one table in a circular. Judgment-based assessment may invite inconsistent decisions, appeals and disputes over why one proposal qualifies while another does not.</p>
  <p>Prescription is not necessarily a failure of imagination. It is often what makes an administrative decision consistent and defensible. A more flexible pathway may require an independent technical panel, published criteria, agreed performance indicators and post-completion verification, together with a credible mechanism to reduce or recover the incentive where commitments are not fulfilled.</p>
  <p>This would be slower and more expensive than counting percentages. It could also favour sophisticated developers and consultants who are better at preparing persuasive submissions. Any successor must therefore ensure that a polished proposal does not outperform a productive system. Not every experiment deserves bonus GFA, and nobody needs another layer of paperwork wearing a more futuristic name.</p>
  <p>There is also a commercial risk. If the incentive is treated as guaranteed development potential, sellers may price it into their expectations and developers may bid it away before deciding how it will be earned. A successor should be large enough to influence an upstream investment decision, but not so large that the land bid depends on receiving it.</p>
  <blockquote>An incentive that cannot say no eventually becomes a discount.</blockquote>
  <h2>What should happen before November</h2>
  <p>The useful next step is neither a blanket extension nor silence. It is a published review of what BET has delivered over its five-year life: how many projects adopted it, what types of development used it, what the additional GFA cost in planning and infrastructure terms, and which measures required genuine changes to design, procurement and coordination.</p>
  <p>The review should also examine completed outcomes. Did projects reduce site manpower, improve quality or provide better information continuity? Did sustainability measures deliver the expected operational performance? Which requirements changed developer behaviour, and which became compliance exercises that looked more transformational in the submission than on the project?</p>
  <p>Five years should have produced a meaningful body of evidence. It would be a waste to let a calendar date substitute for reading it.</p>
  <p>That evidence could support a smaller successor pathway focused on advances beyond the regulatory baseline. Its thresholds should move over time. Once a method becomes mandatory or widely established, it should cease to receive the same reward. Complex en-bloc projects could qualify for a stronger tier, but only where inherited constraints are real and the proposed outcomes correspondingly higher.</p>
  <p>Planning capacity must remain a condition. Innovation cannot override height, traffic, infrastructure or environmental limitations. A productive construction method does not make an overloaded junction less busy.</p>
  <p>For projects still considering BET, the runway is shorter than the November date suggests. The relevant development application must meet the deadline, while technical assessment and acceptance take time. November is the closing date, not the date to begin thinking about it.</p>
  <h2>Retain the principle, move the frontier</h2>
  <p>BET recognised something important about construction transformation. Innovation is not merely the arrival of a machine, platform or prefabricated component. It is the integration of planning, design, manufacturing, regulation and procurement early enough for that system to work.</p>
  <p>That integration imposes cost and risk long before its benefits become visible. BET helped move PPVC, digital delivery, prefabricated MEP and higher environmental performance closer to ordinary practice. If those methods no longer require the same support, the scheme has done part of its job.</p>
  <div className="takeaway"><span>Practitioner takeaway</span><strong>The next scheme should not keep buying what the industry already knows how to do. The frontier has moved. The policy should move with it.</strong></div>
  <h2>Sources consulted</h2>
  <ul><li>Building and Construction Authority — Built Environment Transformation Gross Floor Area Incentive Scheme</li><li>BCA/URA Joint Circular BCA/ITM GFA/2021–11-ES and URA/PB/2021/06-DCG</li><li>Urban Redevelopment Authority — Circular DC21–06</li><li>Building and Construction Authority — Mandatory Higher Green Mark Standard for Government Land Sales sites</li><li>Building and Construction Authority — APCS and PPVC requirements under the Buildability Framework</li></ul>
  <p className="original-note">Originally published on <a href="https://www.linkedin.com/pulse/bet-expiring-transformation-should-hwee-chim-lim-66gwc/" target="_blank" rel="noreferrer">LinkedIn</a> on 4 August 2026.</p>
  <p className="author-note">Lim Hwee Chim is a Singapore property development leader and the founder of Skyline by HC, where she writes about how upstream developer decisions shape construction outcomes.</p>
</>}

export default async function Article({params}:{params:Promise<{slug:string}>}){const {slug}=await params; const a=articles.find(x=>x.slug===slug); if(!a)notFound(); return <Shell><article className="article-page"><header><p className="eyebrow">{a.topic}</p><h1>{a.title}</h1><p className="standfirst">{a.dek}</p><div className="byline"><span>By Lim Hwee Chim</span><span>{a.date} · {a.read} read</span></div></header><div className="article-body">{slug==="bet-is-expiring"?<BetArticle/>:slug==="top-90-day-stress-test"?<TopArticle/>:<><p className="lead">The visible problem usually arrives late. A deadline slips, an interface fails, or a new system cannot be commissioned as intended. By then, the project is already paying for decisions made much earlier.</p><p>This essay forms part of the Skyline by HC launch collection. The full original article will be migrated here as the website becomes the permanent home of the archive.</p><h2>The upstream question</h2><p>Construction performance is often discussed as if productivity begins at the workface. But contractors execute within conditions shaped by development strategy, authority sequencing, design maturity, procurement and the quality of information that reaches them.</p><blockquote>Upstream compression does not disappear. It reappears downstream at greater cost.</blockquote><p>The practical task is not to assign blame upstream. It is to find the earliest point where a clearer decision, interface or feedback loop could materially change the outcome—and to test whether that intervention is proportionate to its cost.</p><div className="takeaway"><span>Practitioner takeaway</span><strong>Look for the first missing decision, not only the final visible failure.</strong></div><p className="author-note">Lim Hwee Chim is a Singapore property development leader and the founder of Skyline by HC, where she writes about how upstream developer decisions shape construction outcomes.</p></>}</div></article><section className="next-read"><p className="eyebrow">Continue reading</p><Link href="/articles">Explore the full article library <span>→</span></Link></section></Shell>}
